avalanche:
  worker_name: avalanche_1

  pool:
    p_1:
      profile:
        queues: [ medium, hard ]
      agents: 1

    p_2:
      profile:
        queues: soft
      agents: 1

    p_3:
      profile:
        queues: "*"
      agents: 3
